@baseUrl = http://localhost:5000

### Login (usuarios precargados)
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "username": "admin",
  "password": "Admin123*"
}

### Refresh (pega el accessToken/refreshToken del login)
POST {{baseUrl}}/auth/refresh
Content-Type: application/json

{
  "accessToken": "PASTE_ACCESS_TOKEN",
  "refreshToken": "PASTE_REFRESH_TOKEN"
}
